### ISSUE TITLE
Fast DP error: 'CLIBD'

### ISSUE THREAD

**Issue by dsclassen** [DiamondLightSource/fast_dp#42]
I'm trying to get fast_dp working on a new CentOS7 machine.

I install cctbx from source
installed fast_dp as per instructions

```
Fast_DP version 1.3
Starting image: /20190501/burn0/lyso5_1_E1_00001.cbf
Running on: als-enable
Number of jobs: 1
Number of cores: 0
Processing images: 1 -> 100
Rotation range: 107.00 -> 207.00
Template: lyso5_1_E1_#####.cbf
Wavelength: 1.25511
Working in: /home/username/process
All autoindexing results:
Lattice      a      b      c  alpha   beta  gamma
Autoindexing failed
Fast DP error: 'CLIBD'
```

From fast_dp.error file:

```
$ cat fast_dp.error 
Traceback (most recent call last):
  File "/home/username/cctbx/base/lib/python2.7/site-packages/fast_dp/fast_dp.py", line 532, in main
    finst.process()
  File "/home/username/cctbx/base/lib/python2.7/site-packages/fast_dp/fast_dp.py", line 263, in process
    self._xds_inp, input_cell=self._input_cell_p1
  File "/home/username/cctbx/base/lib/python2.7/site-packages/fast_dp/autoindex.py", line 133, in autoindex
    spacegroup_to_lattice(r),
  File "/home/username/cctbx/base/lib/python2.7/site-packages/fast_dp/cell_spacegroup.py", line 78, in spacegroup_to_lattice
    os.path.join(os.environ["CLIBD"], "symop.lib"), "r"
  File "/home/username/cctbx/build/../base/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'CLIBD'
```

**Comment by rjgildea** [comment]
Have you sourced a CCP4 environment? This should set the $CLIBD variable (although as of 3 days ago fast_dp should no require $CLIBD https://github.com/DiamondLightSource/fast_dp/commit/d13fcb0c0f099bdedfae5c94fddc09341f462b49).

**Comment by dsclassen** [comment]
that did the trick. sorry for the false alarm.
