### ISSUE TITLE
Fix up for updated DIALS

### ISSUE THREAD

**Issue by graeme-winter** [DiamondLightSource/fast_dp#59]
`fast_dp` has become incompatible with recent dials releases due to deprecation and removal of some features. Please fix.

**Comment by graeme-winter** [comment]
```
Traceback (most recent call last):
  File "/dls/science/users/gw56/dials-dev/modules/fast_dp/fast_dp/fast_dp.py", line 456, in main
    missing = finst.set_start_image(image)
  File "/dls/science/users/gw56/dials-dev/modules/fast_dp/fast_dp/fast_dp.py", line 138, in set_start_image
    self._xds_inp = fast_dp.image_readers.read_image_metadata_dxtbx(
  File "/dls/science/users/gw56/dials-dev/modules/fast_dp/fast_dp/image_readers.py", line 326, in read_image_metadata_dxtbx
    expt = ExperimentList.from_filenames([image])[0]
AttributeError: type object 'ExperimentList' has no attribute 'from_filenames'
```

**Comment by KevinBattaile** [comment]
Will this be updated in PyPI soon so the 'libtbx.pip install --upgrade fast_dp' update mechanism works?

**Comment by graeme-winter** [comment]
Good point, will try and get this out over next couple of days

**Comment by graeme-winter** [comment]
> Will this be updated in PyPI soon so the 'libtbx.pip install --upgrade fast_dp' update mechanism works?

Now on pypi:

```
Ethics-Gradient ~ :( $ pip install -U fast_dp
Requirement already satisfied: fast_dp in ./git/dials/conda_base/lib/python3.10/site-packages (1.6.2)
Collecting fast_dp
  Downloading fast_dp-1.7-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: procrunner in ./git/dials/conda_base/lib/python3.10/site-packages (from fast_dp) (2.3.3)
Downloading fast_dp-1.7-py3-none-any.whl (39 kB)
Installing collected packages: fast_dp
  Attempting uninstall: fast_dp
    Found existing installation: fast_dp 1.6.2
    Uninstalling fast_dp-1.6.2:
      Successfully uninstalled fast_dp-1.6.2
Successfully installed fast_dp-1.7
```
